import type { ExerciseDef } from "./types";

export const EXERCISES: ExerciseDef[] = [
  {
    id: "bench-press",
    name: "Bench Press",
    muscle: "Chest",
    equipment: "Barbell",
    pattern: "push",
    defaultWeightsKg: [40, 50, 60, 70, 80, 90, 100],
    expectedRepsAtWeight: {
      "40": 18,
      "50": 15,
      "60": 12,
      "70": 10,
      "80": 8,
      "90": 5,
      "100": 3,
    },
  },
  {
    id: "squat",
    name: "Back Squat",
    muscle: "Quads",
    equipment: "Barbell",
    pattern: "legs",
    defaultWeightsKg: [40, 60, 80, 100, 120, 140],
    expectedRepsAtWeight: {
      "40": 20,
      "60": 15,
      "80": 12,
      "100": 10,
      "120": 6,
      "140": 3,
    },
  },
  {
    id: "deadlift",
    name: "Deadlift",
    muscle: "Posterior",
    equipment: "Barbell",
    pattern: "pull",
    defaultWeightsKg: [60, 80, 100, 120, 140, 160],
    expectedRepsAtWeight: {
      "60": 15,
      "80": 12,
      "100": 10,
      "120": 8,
      "140": 5,
      "160": 3,
    },
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    muscle: "Shoulders",
    equipment: "Barbell",
    pattern: "push",
    defaultWeightsKg: [20, 30, 40, 50, 60],
    expectedRepsAtWeight: {
      "20": 15,
      "30": 12,
      "40": 10,
      "50": 6,
      "60": 3,
    },
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    muscle: "Back",
    equipment: "Bodyweight",
    pattern: "pull",
    defaultWeightsKg: [0, 5, 10, 15, 20],
    expectedRepsAtWeight: {
      "0": 12,
      "5": 10,
      "10": 8,
      "15": 5,
      "20": 3,
    },
  },
  {
    id: "row",
    name: "Barbell Row",
    muscle: "Back",
    equipment: "Barbell",
    pattern: "pull",
    defaultWeightsKg: [40, 50, 60, 70, 80],
    expectedRepsAtWeight: {
      "40": 15,
      "50": 12,
      "60": 10,
      "70": 8,
      "80": 5,
    },
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    muscle: "Hamstrings",
    equipment: "Barbell",
    pattern: "legs",
    defaultWeightsKg: [40, 60, 80, 100, 120],
    expectedRepsAtWeight: {
      "40": 15,
      "60": 12,
      "80": 10,
      "100": 8,
      "120": 5,
    },
  },
  {
    id: "lunges",
    name: "Walking Lunges",
    muscle: "Quads",
    equipment: "Dumbbell",
    pattern: "legs",
    defaultWeightsKg: [10, 15, 20, 25, 30],
    expectedRepsAtWeight: {
      "10": 20,
      "15": 16,
      "20": 12,
      "25": 10,
      "30": 8,
    },
  },
  {
    id: "dip",
    name: "Dip",
    muscle: "Triceps",
    equipment: "Bodyweight",
    pattern: "push",
    defaultWeightsKg: [0, 5, 10, 15, 20],
    expectedRepsAtWeight: {
      "0": 15,
      "5": 12,
      "10": 10,
      "15": 6,
      "20": 4,
    },
  },
  {
    id: "plank-load",
    name: "Loaded Plank Hold",
    muscle: "Core",
    equipment: "Plate",
    pattern: "core",
    defaultWeightsKg: [0, 10, 20, 30],
    expectedRepsAtWeight: {
      "0": 60,
      "10": 45,
      "20": 30,
      "30": 20,
    },
  },
];

export function getExercise(id: string): ExerciseDef | undefined {
  return EXERCISES.find((e) => e.id === id);
}
