import type { FoodItem } from "./types";

export const FOODS: FoodItem[] = [
  {
    id: "chicken-breast",
    name: "Grilled chicken breast",
    servingLabel: "150g",
    calories: 248,
    proteinG: 46,
    carbsG: 0,
    fatG: 5,
    fiberG: 0,
    sodiumMg: 110,
    potassiumMg: 540,
    calciumMg: 15,
    ironMg: 1,
    magnesiumMg: 40,
    tags: ["protein", "lean", "dinner", "lunch"],
  },
  {
    id: "salmon",
    name: "Baked salmon",
    servingLabel: "150g",
    calories: 280,
    proteinG: 34,
    carbsG: 0,
    fatG: 16,
    fiberG: 0,
    sodiumMg: 90,
    potassiumMg: 520,
    calciumMg: 20,
    ironMg: 0.8,
    magnesiumMg: 45,
    tags: ["protein", "omega3", "dinner"],
  },
  {
    id: "eggs",
    name: "Whole eggs",
    servingLabel: "2 large",
    calories: 140,
    proteinG: 12,
    carbsG: 1,
    fatG: 10,
    fiberG: 0,
    sodiumMg: 140,
    potassiumMg: 140,
    calciumMg: 50,
    ironMg: 1.2,
    magnesiumMg: 12,
    tags: ["protein", "breakfast"],
  },
  {
    id: "oats",
    name: "Rolled oats with milk",
    servingLabel: "1 bowl",
    calories: 320,
    proteinG: 12,
    carbsG: 48,
    fatG: 8,
    fiberG: 6,
    sodiumMg: 80,
    potassiumMg: 350,
    calciumMg: 180,
    ironMg: 2.5,
    magnesiumMg: 70,
    tags: ["carbs", "breakfast", "fiber"],
  },
  {
    id: "rice-bowl",
    name: "Brown rice bowl",
    servingLabel: "200g cooked",
    calories: 220,
    proteinG: 5,
    carbsG: 46,
    fatG: 2,
    fiberG: 3.5,
    sodiumMg: 5,
    potassiumMg: 150,
    calciumMg: 20,
    ironMg: 1,
    magnesiumMg: 65,
    tags: ["carbs", "lunch", "dinner"],
  },
  {
    id: "sweet-potato",
    name: "Baked sweet potato",
    servingLabel: "200g",
    calories: 180,
    proteinG: 4,
    carbsG: 41,
    fatG: 0.3,
    fiberG: 6,
    sodiumMg: 70,
    potassiumMg: 750,
    calciumMg: 60,
    ironMg: 1.2,
    magnesiumMg: 40,
    tags: ["carbs", "fiber", "dinner"],
  },
  {
    id: "greek-yogurt",
    name: "Greek yogurt",
    servingLabel: "200g",
    calories: 160,
    proteinG: 20,
    carbsG: 8,
    fatG: 4,
    fiberG: 0,
    sodiumMg: 70,
    potassiumMg: 280,
    calciumMg: 220,
    ironMg: 0.1,
    magnesiumMg: 25,
    tags: ["protein", "breakfast", "snack"],
  },
  {
    id: "avocado-toast",
    name: "Avocado toast",
    servingLabel: "1 slice",
    calories: 290,
    proteinG: 7,
    carbsG: 28,
    fatG: 18,
    fiberG: 8,
    sodiumMg: 220,
    potassiumMg: 480,
    calciumMg: 40,
    ironMg: 1.5,
    magnesiumMg: 50,
    tags: ["fats", "breakfast", "fiber"],
  },
  {
    id: "salad-bowl",
    name: "Mixed greens salad + vinaigrette",
    servingLabel: "1 large bowl",
    calories: 180,
    proteinG: 5,
    carbsG: 14,
    fatG: 12,
    fiberG: 5,
    sodiumMg: 280,
    potassiumMg: 420,
    calciumMg: 80,
    ironMg: 1.8,
    magnesiumMg: 35,
    tags: ["veg", "lunch", "fiber"],
  },
  {
    id: "steak",
    name: "Sirloin steak",
    servingLabel: "180g",
    calories: 360,
    proteinG: 48,
    carbsG: 0,
    fatG: 18,
    fiberG: 0,
    sodiumMg: 100,
    potassiumMg: 580,
    calciumMg: 20,
    ironMg: 4,
    magnesiumMg: 40,
    tags: ["protein", "iron", "dinner"],
  },
  {
    id: "banana",
    name: "Banana",
    servingLabel: "1 medium",
    calories: 105,
    proteinG: 1.3,
    carbsG: 27,
    fatG: 0.4,
    fiberG: 3,
    sodiumMg: 1,
    potassiumMg: 420,
    calciumMg: 6,
    ironMg: 0.3,
    magnesiumMg: 32,
    tags: ["carbs", "snack", "potassium"],
  },
  {
    id: "whey",
    name: "Whey protein shake",
    servingLabel: "1 scoop + water",
    calories: 120,
    proteinG: 24,
    carbsG: 3,
    fatG: 1,
    fiberG: 0,
    sodiumMg: 130,
    potassiumMg: 160,
    calciumMg: 120,
    ironMg: 0.4,
    magnesiumMg: 20,
    tags: ["protein", "snack", "postworkout"],
  },
  {
    id: "quinoa-bowl",
    name: "Quinoa veggie bowl",
    servingLabel: "1 bowl",
    calories: 340,
    proteinG: 14,
    carbsG: 48,
    fatG: 10,
    fiberG: 8,
    sodiumMg: 260,
    potassiumMg: 560,
    calciumMg: 70,
    ironMg: 3.5,
    magnesiumMg: 90,
    tags: ["carbs", "fiber", "lunch", "iron"],
  },
  {
    id: "almonds",
    name: "Almonds",
    servingLabel: "30g",
    calories: 170,
    proteinG: 6,
    carbsG: 6,
    fatG: 15,
    fiberG: 3.5,
    sodiumMg: 0,
    potassiumMg: 200,
    calciumMg: 75,
    ironMg: 1,
    magnesiumMg: 75,
    tags: ["fats", "snack", "magnesium"],
  },
  {
    id: "burger",
    name: "Beef burger + bun",
    servingLabel: "1 burger",
    calories: 540,
    proteinG: 28,
    carbsG: 40,
    fatG: 30,
    fiberG: 2,
    sodiumMg: 780,
    potassiumMg: 360,
    calciumMg: 90,
    ironMg: 3.2,
    magnesiumMg: 35,
    tags: ["indulgent", "lunch", "dinner"],
  },
  {
    id: "pasta",
    name: "Pasta with tomato sauce",
    servingLabel: "1 plate",
    calories: 420,
    proteinG: 14,
    carbsG: 72,
    fatG: 8,
    fiberG: 5,
    sodiumMg: 520,
    potassiumMg: 380,
    calciumMg: 60,
    ironMg: 2.5,
    magnesiumMg: 50,
    tags: ["carbs", "dinner"],
  },
];

export function getFood(id: string): FoodItem | undefined {
  return FOODS.find((f) => f.id === id);
}
